### ISSUE TITLE
Exception occurred with .vcxproj format.

### ISSUE THREAD

**Issue by AlexanderJ-ULabs** [dfederm/ReferenceTrimmer#1]
Your code is super well written by the way. Great tool!

This occurred when a `.vxcproj` file of C++ was part of my solution. I was able to add a conditional skip to the source and re-build it for my testing.

```
Unhandled Exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args) in E:\A\_work\17\s\src\Shared\ProjectErrorUtilities.cs:line 440
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpression(String directoryOfImportingFile, ProjectImportElement importElement, String unescapedExpression, Boolean throwOnFileNotExistsError, List`1& imports) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2641
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImportsFromUnescapedImportExpressionConditioned(String directoryOfImportingFile, ProjectImportElement importElement, List`1& projects, Boolean throwOnFileNotExistsError) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2422
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, ProjectImportElement importElement) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2215
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 2070
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 1109
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(ILoggingService loggingService, BuildEventContext buildEventContext) in E:\A\_work\17\s\src\Build\Evaluation\Evaluator.cs:line 794
   at Microsoft.Build.Evaluation.Project.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 2641
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 2634
   at Microsoft.Build.Evaluation.Project.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings) in E:\A\_work\17\s\src\Build\Definition\Project.cs:line 2711
   at Buildalyzer.ProjectAnalyzer.Load()
   at ReferenceReducer.Project.Create(AnalyzerManager manager, Options options, String projectFile) in C:\Users\David\Code\ReferenceTrimmer\src\Project.cs:line 49
   at ReferenceReducer.Project.GetProject(AnalyzerManager manager, Options options, String projectFile) in C:\Users\David\Code\ReferenceTrimmer\src\Project.cs:line 39
   at ReferenceReducer.Program.Run(Options options) in C:\Users\David\Code\ReferenceTrimmer\src\Program.cs:line 48
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at ReferenceReducer.Program.Main(String[] args) in C:\Users\David\Code\ReferenceTrimmer\src\Program.cs:line 20

```

**Comment by dfederm** [comment]
@AlexanderJ-ULabs thanks for the report. Can you show me what the `<Import>` looks like?

**Comment by Sebazzz** [comment]
I have a similar issue in a standard Web Forms application.

    Unhandled Exception: Microsoft.Build.Exceptions.InvalidProjectFileException: The imported project "C:\Program Files\dotnet\sdk\2.1.4\Microsoft\VisualStudio\v15.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The import statement in question:

    <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />

Workaround is to temporary remove the offending import.

**Comment by dfederm** [comment]
@Sebazzz it's looking for it under the dotnet dir. The library I use to do the MsBuild parsing (Buildalyzer) seems to always use the dotnet install of MsBuild when the host application (ReferenceTrimmer) uses .NET Core.

If you downloaded the source and built it yourself, try changing it to target .NET Framework, building that, and seeing if that works. I'll also look into producing both a .NET Core and .NET Framework flavor of ReferenceTrimmer on my end to make it easier.

**Comment by Sebazzz** [comment]
Thanks for your quick follow-up. I will try soon.

**Comment by Sebazzz** [comment]
@dfederm That fix works! Thanks.
